name: Test

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        default: ubuntu-latest
        type: string

jobs:
  test:
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix:
        python_version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
          hatch env create

      - name: Lint and typecheck
        run: |
          hatch run lint-check

      - name: Test
        run: |
          hatch run test
